---
- name:                   "Ensure openstack network is created"
  os_network:
    name:                 "{{ osappliances_openstack_project_name }}-net"
    state:                present
    external:             false
    mtu:                  1450
- name:                   "Ensure openstack subnet is created"
  os_subnet:
    name:                 "{{ osappliances_openstack_project_name }}-snet"
    state:                present
    network_name:         "{{ osappliances_openstack_project_name }}-net"
    cidr:                 "{{ osappliances_cidr }}"
    enable_dhcp:          true
- name:                   "Ensure openstack router is created"
  os_router:
    name:                 "{{ osappliances_openstack_project_name }}-rt"
    state:                present
    network:              "{{ osappliances_os_router_network }}"
    interfaces:
      - "{{ osappliances_openstack_project_name }}-snet"
- name:                   "Ensure openstack network security group is created"
  os_security_group:
    name:                 "{{ osappliances_openstack_project_name }}-nsg"
    state:                present
    description:          "{{ osappliances_openstack_project_name }} network security group" # yamllint disable-line rule:line-length
- name:                   "Ensure openstack icmp rule is created"
  os_security_group_rule:
    security_group:       "{{ osappliances_openstack_project_name }}-nsg"
    state:                present
    direction:            ingress
    ethertype:            IPv4
    interface:            public
    protocol:             icmp
    remote_ip_prefix:     0.0.0.0/0
- name:                   "Ensure openstack tcp rules are created"
  os_security_group_rule:
    security_group:       "{{ osappliances_openstack_project_name }}-nsg"
    state:                present
    direction:            ingress
    ethertype:            IPv4
    interface:            public
    port_range_max:       "{{ item }}"
    port_range_min:       "{{ item }}"
    protocol:             tcp
    remote_ip_prefix:     0.0.0.0/0
  loop:                   [ 22, 80, 443 ]
- name:                   "Ensure openstack key pair is created"
  os_keypair:
    name:                 "{{ osappliances_openstack_project_name }}-key"
    state:                present
  register:               res_os_keypair
- name:                   "Ensure that the public key is backed up if it has been created" # yamllint disable-line rule:line-length
  copy:
    content:              "{{ res_os_keypair.key.public_key }}"
    dest:                 "~/.ssh/{{ osappliances_openstack_project_name }}.pub"
    mode:                 '0644'
  when:                   res_os_keypair.changed
- name:                   "Ensure that the private key is backed up if it has been created" # yamllint disable-line rule:line-length
  copy:
    content:              "{{ res_os_keypair.key.private_key }}"
    dest:                 "~/.ssh/{{ osappliances_openstack_project_name }}"
    mode:                 '0600'
  when:                   res_os_keypair.changed
- name:                   "Ensure openstack server group is created"
  os_server_group:
    name:                 "{{ osappliances_openstack_project_name }}-srg"
    state:                present
    policies:
      - affinity
